### ISSUE TITLE
OpenAPI file will not load using relative link

### ISSUE THREAD

**Issue by AX-LLaidley** [scalar/scalar#6915]
### What happens?

When I try to load the OpenAPI file using a relative link, it isn't loaded. I instead receive parser errors and CORS errors in the developer console, in Chrome. This happens when using either YAML or JSON format.

### What did you expect to happen?

I expected that the OpenAPI file would be loaded and the API documentation to be shown.

**Comment by xC0dex** [comment]
Hey @AX-LLaidley,

Thanks for creating an issue! Could you please share a bit about your environment? Which integration/framework do you use? 👀

**Comment by AX-LLaidley** [comment]
We're using the HTML integration within a XHTML page. We use MadCap Flare, and our documentation site is hosted on Flare Online (MadCap Central). I'll attach a copy of the .htm file for the page.

Our OAS files are managed in another repo as split definitions, which then get bundled and copied to the docs site repo using a GHA. I can provide one of our bundled OAS files for test purposes.

This was working fine when I was linking to the OAS files when they were stored in one of our public repos, however I'm trying to minimize the number of places we're storing the definition files so that it's easier to keep them up to date. Linking to them in the repo we use for managing the API files wouldn't be possible as that repo resides in a private Github org and I'm unable to have anything public within that org.

[Automox API Reference.htm](https://github.com/user-attachments/files/22498895/Automox.API.Reference.htm)

[ax-console-bundle.json](https://github.com/user-attachments/files/22498920/ax-console-bundle.json)

**Comment by xC0dex** [comment]
Thanks for sharing! Relative URLs are not a problem in general. But I guess having the `../` as part of the URL is. 

@hanspagel, should we add support for this? Maybe we can build the URL first instead of passing them straight to fetch.

**Comment by AX-LLaidley** [comment]
Is this fixed now? Asking because I'm still running into the same issue, and I made sure I'm loading v1.36.2. Am I missing something?

**Comment by xC0dex** [comment]
Hey @AX-LLaidley,

Fixed but not released. It will be part of the next release. 🥳

**Comment by AX-LLaidley** [comment]
I tried testing it again with v1.37.0 and I'm still having trouble with it not loading the local files. I'm getting a 403 on the fetch operation, as well as a 403 on the proxy. Wondering if I'm still missing something.

**Comment by xC0dex** [comment]
It looks like the OpenAPI document isn’t publicly accessible. That would explain the 403 errors you’re seeing on both the fetch and proxy requests. You may need to make the spec available or adjust permissions so it can be loaded properly.
